# Generated by Django 5.2 on 2025-04-02 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=8)),
                ('class_name', models.CharField(max_length=10)),
                ('date', models.CharField(max_length=3)),
                ('time', models.TimeField()),
            ],
        ),
    ]
