# Generated by Django 5.2 on 2025-04-25 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('class_name', models.CharField(max_length=50)),
                ('id_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('IsLab', models.BooleanField(default=False)),
                ('Section_Number', models.IntegerField(default=1)),
                ('Instructor', models.CharField(default='To Be Assigned', max_length=50)),
                ('Date', models.CharField(max_length=3)),
                ('Time', models.CharField(max_length=4)),
                ('Location', models.CharField(default='To Be Assigned', max_length=50)),
                ('Enrollment_max', models.IntegerField(default=100)),
                ('Enrollment', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'app_course',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cart')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.course')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id_number', models.CharField(default='-1', max_length=8, primary_key=True, serialize=False)),
                ('first_name', models.CharField(default='Jane', max_length=50)),
                ('last_name', models.CharField(default='Smith', max_length=50)),
                ('password', models.CharField(default='abc123', max_length=50)),
                ('enrolled_courses', models.ManyToManyField(blank=True, related_name='enrolled_students', to='app.course')),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.AddField(
            model_name='cart',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student'),
        ),
    ]
