# Generated by Django 5.2 on 2025-04-25 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='course',
            field=models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.CASCADE, to='app.course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='class_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='id_number',
            field=models.CharField(default='-1', max_length=8, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterModelTable(
            name='course',
            table=None,
        ),
    ]
