# Generated by Django 5.2 on 2025-04-15 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('shoppingCart1', models.CharField(max_length=8)),
                ('shoppingCart2', models.CharField(max_length=8)),
                ('shoppingCart3', models.CharField(max_length=8)),
                ('shoppingCart4', models.CharField(max_length=8)),
                ('shoppingCart5', models.CharField(max_length=8)),
                ('shoppingCart6', models.CharField(max_length=8)),
                ('shoppingCart7', models.CharField(max_length=8)),
                ('shoppingCart8', models.CharField(max_length=8)),
                ('shoppingCart9', models.CharField(max_length=8)),
                ('shoppingCart10', models.CharField(max_length=8)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='section_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='course',
            name='time',
            field=models.CharField(max_length=4),
        ),
    ]
