# Generated by Django 5.2 on 2025-04-15 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_student_course_section_number_alter_course_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.CharField(default='', max_length=20),
        ),
    ]
