# Generated by Django 5.2 on 2025-04-15 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_course_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='enrollment',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='enrollment_max',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='course',
            name='islab',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='location',
            field=models.CharField(default='', max_length=10),
        ),
    ]
