# Generated by Django 5.2 on 2025-04-15 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_course_enrollment_course_enrollment_max_course_islab_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='date',
            new_name='Date',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='enrollment',
            new_name='Enrollment',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='enrollment_max',
            new_name='Enrollment_max',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='islab',
            new_name='IsLab',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='location',
            new_name='Location',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='section_number',
            new_name='Section_Number',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='time',
            new_name='Time',
        ),
        migrations.RemoveField(
            model_name='course',
            name='instructor',
        ),
        migrations.AddField(
            model_name='course',
            name='Instructor',
            field=models.CharField(default='To Be Assigned', max_length=20),
        ),
    ]
