# Generated by Django 5.2 on 2025-04-15 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_date_course_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Location',
            field=models.CharField(default='To Be Assigned', max_length=10),
        ),
    ]
