# Generated by Django 5.2 on 2025-04-24 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_course_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='shoppingCart1',
        ),
        migrations.RemoveField(
            model_name='student',
            name='shoppingCart10',
        ),
        migrations.RemoveField(
            model_name='student',
            name='shoppingCart2',
        ),
        migrations.RemoveField(
            model_name='student',
            name='shoppingCart3',
        ),
        migrations.RemoveField(
            model_name='student',
            name='shoppingCart4',
        ),
        migrations.RemoveField(
            model_name='student',
            name='shoppingCart5',
        ),
        migrations.RemoveField(
            model_name='student',
            name='shoppingCart6',
        ),
        migrations.RemoveField(
            model_name='student',
            name='shoppingCart7',
        ),
        migrations.RemoveField(
            model_name='student',
            name='shoppingCart8',
        ),
        migrations.RemoveField(
            model_name='student',
            name='shoppingCart9',
        ),
        migrations.AddField(
            model_name='student',
            name='first_name',
            field=models.CharField(default='Jane', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=models.CharField(default='Smith', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='id_number',
            field=models.CharField(default='-1', max_length=8),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default='abc123', max_length=50),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cart')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.course')),
            ],
        ),
    ]
