# Generated by Django 5.2 on 2025-04-24 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_student_name_remove_student_shoppingcart1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AlterField(
            model_name='student',
            name='id_number',
            field=models.CharField(default='-1', max_length=8, primary_key=True, serialize=False),
        ),
    ]
