# Generated by Django 5.2 on 2025-04-24 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_student_id_alter_student_id_number'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='student',
        ),
    ]
