# Generated by Django 5.2 on 2025-04-25 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_student_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table=None,
        ),
    ]
