# Generated by Django 5.2 on 2025-04-25 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_student_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Location',
            field=models.CharField(default='To Be Assigned', max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='class_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='id_number',
            field=models.CharField(max_length=20),
        ),
    ]
