# Generated by Django 5.2 on 2025-04-25 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_course_location_alter_course_class_name_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='app_student',
        ),
    ]
