# Generated by Django 5.2 on 2025-04-25 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_student_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='class_name',
            field=models.CharField(max_length=50),
        ),
    ]
