# Generated by Django 5.2 on 2025-04-25 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_course_class_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Instructor',
            field=models.CharField(default='To Be Assigned', max_length=30),
        ),
        migrations.AlterField(
            model_name='course',
            name='Location',
            field=models.CharField(default='To Be Assigned', max_length=30),
        ),
        migrations.AlterField(
            model_name='course',
            name='id_number',
            field=models.CharField(max_length=30),
        ),
    ]
