# Generated by Django 5.2 on 2025-04-25 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_student_enrolled_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='enrolled_courses',
        ),
        migrations.AlterField(
            model_name='course',
            name='class_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='id_number',
            field=models.CharField(max_length=20),
        ),
    ]
