# Generated by Django 5.2 on 2025-04-25 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_student_enrolled_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='id',
        ),
        migrations.AlterField(
            model_name='course',
            name='id_number',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
