# Generated by Django 5.2 on 2025-04-25 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_remove_course_id_alter_course_id_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='id_number',
            field=models.CharField(default='-1', max_length=8, primary_key=True, serialize=False, unique=True),
        ),
    ]
