# Generated by Django 5.2 on 2025-04-25 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_student_id_number'),
    ]

    operations = [
        migrations.RunSQL(
            """
            ALTER TABLE app_cartitem
            ALTER COLUMN course_id TYPE varchar(8)
            USING course_id::varchar;
            """,
            reverse_sql="""
            ALTER TABLE app_cartitem
            ALTER COLUMN course_id TYPE bigint
            USING course_id::bigint;
            """
        )
    ]
