# Generated by Django 5.1.7 on 2025-03-09 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('id_number', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='img')),
                ('category', models.CharField(choices=[('Math', 'MATH'), ('Computer_Science', 'CPTS'), ('Biology', 'BIO'), ('Physics', 'PHYS'), ('Chemistry', 'CHEM'), ('History', 'HIST')], max_length=20)),
            ],
        ),
    ]
